/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api

import com.snowdango.bijouk.api.model.BasicResponse
import com.snowdango.bijouk.api.model.NowPlayingResponse
import com.snowdango.bijouk.api.model.PlayRequestBody
import com.snowdango.bijouk.api.model.PlaybackQueueChangeToIndexPostRequest
import com.snowdango.bijouk.api.model.PlaybackQueueMoveToPositionPostRequest
import com.snowdango.bijouk.api.model.PlaybackSeekPostRequest
import com.snowdango.bijouk.api.model.PlaybackShuffleModeGet200Response
import com.snowdango.bijouk.api.model.QueueResponseData

import org.openapitools.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class CiderRpcApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * server is active
     * 
     * @param body  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackActiveGet(body: kotlin.Any? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/playback/active",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Control Song next
     * 
     * @param body  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackNextPost(body: kotlin.Any? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/next",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Get Now Playing Song
     * 
     * @param body  (optional)
     * @return NowPlayingResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackNowPlayingGet(body: kotlin.Any? = null): HttpResponse<NowPlayingResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/playback/now-playing",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Play Item
     * 
     * @param playRequestBody  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackPlayItemPost(playRequestBody: PlayRequestBody? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = playRequestBody

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/play-item",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Play Item Later
     * 
     * @param playRequestBody  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackPlayLaterPost(playRequestBody: PlayRequestBody? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = playRequestBody

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/play-later",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Play Item Next
     * 
     * @param playRequestBody  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackPlayNextPost(playRequestBody: PlayRequestBody? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = playRequestBody

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/play-next",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Control Play Pause State
     * 
     * @param body  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackPlaypausePost(body: kotlin.Any? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/playpause",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Control Song previous
     * 
     * @param body  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackPreviousPost(body: kotlin.Any? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/previous",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Change Queue Index
     * 
     * @param playbackQueueChangeToIndexPostRequest  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackQueueChangeToIndexPost(playbackQueueChangeToIndexPostRequest: PlaybackQueueChangeToIndexPostRequest? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = playbackQueueChangeToIndexPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/queue/change-to-index",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Clear Queue
     * 
     * @param body  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackQueueClearQueuePost(body: kotlin.Any? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/queue/clear-queue",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Get Queue State
     * 
     * @param body  (optional)
     * @return kotlin.collections.List<QueueResponseData>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackQueueGet(body: kotlin.Any? = null): HttpResponse<kotlin.collections.List<QueueResponseData>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/playback/queue",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<PlaybackQueueGetResponse>().map { value }
    }


    @Serializable(PlaybackQueueGetResponse.Companion::class)
    private class PlaybackQueueGetResponse(val value: List<QueueResponseData>) {
        companion object : KSerializer<PlaybackQueueGetResponse> {
            private val serializer: KSerializer<List<QueueResponseData>> = serializer<List<QueueResponseData>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: PlaybackQueueGetResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = PlaybackQueueGetResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Move Queue
     * 
     * @param playbackQueueMoveToPositionPostRequest  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackQueueMoveToPositionPost(playbackQueueMoveToPositionPostRequest: PlaybackQueueMoveToPositionPostRequest? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = playbackQueueMoveToPositionPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/queue/move-to-position",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Control Song seek
     * 
     * @param playbackSeekPostRequest  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackSeekPost(playbackSeekPostRequest: PlaybackSeekPostRequest? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = playbackSeekPostRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/seek",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Get Shuffle Mode
     * 
     * @param body  (optional)
     * @return PlaybackShuffleModeGet200Response
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackShuffleModeGet(body: kotlin.Any? = null): HttpResponse<PlaybackShuffleModeGet200Response> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/playback/shuffle-mode",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Shuffle Mode toggle change
     * 
     * @param body  (optional)
     * @return BasicResponse
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun playbackToggleShufflePost(body: kotlin.Any? = null): HttpResponse<BasicResponse> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = body

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/playback/toggle-shuffle",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
