[versions]
version = "0.0.2"
sdk-target = "36"
sdk-min = "30"

agp = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.4"
coreKtx = "1.17.0"
testRunner = "1.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.00"
constraint = "1.1.1"
material3 = "1.5.0-alpha11"
navigation = "2.9.6"
splash = "1.2.0"
window = "1.5.1"
media = "1.7.1"
paging = "3.3.6"
room = "2.8.4"
sqlite-bundled = "2.6.2"
koin = "4.1.1"
coroutine = "1.10.2"
ktor = "3.3.3"
serialization = "1.9.0"
kolor = "4.0.5"
appcompat = "1.7.1"
materialVersion = "1.13.0"
coil = "3.3.0"
kmp-socket = "1.4.0"
ktlint = "14.0.1"
detekt = "1.23.8"
detekt-compose = "0.5.2"
dokka = "2.1.0"
immutable = "0.4.0"
compose-settings = "2.23.0"
aboutLibraries = "13.2.1"
markdown = "0.5.8"
kmlogger = "2.1.0"
url-encoder = "1.6.0"
google-services = "4.4.4"
firebase-bom = "34.7.0"
firebase-crashlytics = "3.0.6"
deploygate = "2.9.0"
qrscanner = "0.6.0"
openapi = "7.18.0"
datastore = "1.2.0"
core = "1.7.0"
palette = "1.0.0"

[libraries]
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-plugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
deploygate-plugin = { group = "com.deploygate", name = "gradle", version.ref = "deploygate" }
openapi-plugin = { group = "org.openapitools", name = "openapi-generator-gradle-plugin", version.ref = "openapi" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
material-icon = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }

# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" } # 1.4.0が使いたいだけなのでbomでreleaseされたらversion設定を外す
androidx-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-material2 = { group = "androidx.compose.material", name = "material" }
androidx-constraint = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraint" }

androidx-palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }

# datastore
androidx-dataStorePreference = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# window
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }

# media
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }

# settings
composeSettings-ui = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "compose-settings" }
composeSettings-ui-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "compose-settings" }

# paging
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

# room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite-bundled" }

# koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }

# coroutine
kotlinx-coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
kotlinx-coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }

# Immutable
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutable" }

# ktor client
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-content = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-socket = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktor-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-ios = { group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }

# socket
kmp-socket = { group = "com.piasy", name = "kmp-socketio", version.ref = "kmp-socket" }

url-encoder = { group = "net.thauvin.erik.urlencoder", name = "urlencoder-lib", version.ref = "url-encoder" }

# serialization
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

# material kolor
material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "kolor" }

# coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# detekt-compose
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }

# aboutLibraries
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }

# qrkit
qrscanner = { group = "io.github.kalinjul.easyqrscan", name = "scanner", version.ref = "qrscanner" }

# markdown
markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "markdown" }

# kmlogger
kmlogger = { group = "com.diamondedge", name = "logging", version.ref = "kmlogger" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

# ktlint
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

# detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
# dokka
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

# aboutLibraries
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }

# deploygate
deploygate = { id = "deploygate" }

# openapi
openapi = { id = "org.openapi.generator" }
android-lint = { id = "com.android.lint", version.ref = "agp" }

[bundles]
test = ["junit"]
android-test = ["androidx-junit", "androidx-espresso-core", "androidx-ui-test-junit4", "androidx-runner"]
android-debug = ["androidx-ui-tooling", "androidx-ui-test-manifest"]
android-base = ["androidx-core-ktx", "androidx-lifecycle-runtime-ktx", "androidx-window"]
android-compose = ["androidx-activity-compose", "androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling-preview", "androidx-material3", "androidx-navigation", "androidx-material2", "androidx-material3-window", "androidx-material3-adaptive"]
settings-compose = ["composeSettings-ui", "composeSettings-ui-extended"]
aboutlibraries = ["aboutlibraries-core", "aboutlibraries-compose-core", "aboutlibraries-compose-m3"]
paging = ["paging-runtime", "paging-compose"]
room = ["room-runtime", "room-ktx", "room-paging"]
koin = ["koin-android", "koin-compose"]
coroutine = ["kotlinx-coroutine-android"]
ktor = ["ktor-core", "ktor-android", "ktor-content", "ktor-logging", "ktor-serialization", "kotlinx-serialization", "ktor-socket"]
coil = ["coil-compose", "coil-ktor"]
detekt = ["detekt-formatting", "detekt-compose"]




