[versions]
agp = "8.9.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
coreKtx = "1.15.0"
testRunner = " 1.6.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.03.01"
material = "1.7.8"
navigation = "2.8.9"
splash = "1.0.1"
room = "2.6.1"
koin = "4.0.2"
coroutine = "1.10.1"
ktor = "3.1.1"
serialization = "1.8.0"
kolor = "2.0.2"
appcompat = "1.7.0"
materialVersion = "1.12.0"
coil = "3.1.0"
socket = "2.1.2"
compose-lint = "1.4.2"
ktlint = "12.1.2"
detekt = "1.23.8"
detekt-compose = "0.4.22"
dokka = "2.0.0"
immutable = "0.3.8"
compose-settings = "2.10.0"
aboutLibraries = "12.0.0"

[libraries]
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-plugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
material-icon = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }

# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material2 = { group = "androidx.compose.material", name = "material" }

# settings
composeSettings-ui = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "compose-settings" }
composeSettings-ui-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "compose-settings" }

# room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

# koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }

# coroutine
kotlinx-coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }

# Immutable
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutable" }

# ktor client
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-content = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-socket = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }

# socket
socket-io = { group = "io.socket", name = "socket.io-client", version.ref = "socket" }

# serialization
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

# material kolor
material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "kolor" }

# coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# detekt-compose
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "detekt-compose" }

# aboutLibraries
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }


androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# ktlint
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

# detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
# dokka
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

# aboutLibraries
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }

[bundles]
test = ["junit"]
android-test = ["androidx-junit", "androidx-espresso-core", "androidx-ui-test-junit4", "androidx-runner"]
android-debug = ["androidx-ui-tooling", "androidx-ui-test-manifest"]
android-base = ["androidx-core-ktx", "androidx-lifecycle-runtime-ktx"]
android-compose = ["androidx-activity-compose", "androidx-ui", "androidx-ui-graphics", "androidx-ui-tooling-preview", "androidx-material3", "androidx-navigation", "androidx-material2"]
settings-compose = ["composeSettings-ui", "composeSettings-ui-extended"]
aboutlibraries = ["aboutlibraries-core", "aboutlibraries-compose-core", "aboutlibraries-compose-m3"]
room = ["room-runtime", "room-ktx", "room-paging"]
koin = ["koin-android", "koin-compose"]
coroutine = ["kotlinx-coroutine"]
ktor = ["ktor-core", "ktor-android", "ktor-content", "ktor-logging", "ktor-serialization", "kotlinx-serialization", "ktor-socket"]
coil = ["coil-compose", "coil-ktor"]
detekt = ["detekt-formatting", "detekt-compose"]




