package com.snowdango.bijouk.domain.api.entity

data class PlayBackData(
    val albumName: String,
    val artistName: String,
    val artwork: Artwork,
    val audioLocale: String?,
    val audioTraits: List<String>?,
    val composerName: String? = null,
    val currentPlaybackTime: Double,
    val discNumber: Int?,
    val durationInMillis: Int,
    val genreNames: List<String>?,
    val hasLyrics: Boolean,
    val hasTimeSyncedLyrics: Boolean?,
    val inFavorites: Boolean,
    val inLibrary: Boolean,
    val isAppleDigitalMaster: Boolean?,
    val isMasteredForItunes: Boolean?,
    val isVocalAttenuationAllowed: Boolean?,
    val isrc: String?,
    val name: String,
    val playParams: PlayParams?,
    val previews: List<Preview>?,
    val releaseDate: String?,
    val remainingTime: Double,
    val repeatMode: Int,
    val shuffleMode: Int,
    val trackNumber: Int?,
    val url: String,
)
