/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.CiderRpcApi
import com.snowdango.bijouk.api.model.BasicResponse
import com.snowdango.bijouk.api.model.NowPlayingResponse
import com.snowdango.bijouk.api.model.QueueResponseData

class CiderRpcApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CiderRpcApi
        //val apiInstance = CiderRpcApi()

        // to test activeGet
        should("test activeGet") {
            // uncomment below to test activeGet
            //val result : BasicResponse = apiInstance.activeGet()
            //result shouldBe ("TODO")
        }

        // to test nextPost
        should("test nextPost") {
            // uncomment below to test nextPost
            //val result : BasicResponse = apiInstance.nextPost()
            //result shouldBe ("TODO")
        }

        // to test nowPlayingGet
        should("test nowPlayingGet") {
            // uncomment below to test nowPlayingGet
            //val result : NowPlayingResponse = apiInstance.nowPlayingGet()
            //result shouldBe ("TODO")
        }

        // to test playpausePost
        should("test playpausePost") {
            // uncomment below to test playpausePost
            //val result : BasicResponse = apiInstance.playpausePost()
            //result shouldBe ("TODO")
        }

        // to test previousPost
        should("test previousPost") {
            // uncomment below to test previousPost
            //val result : BasicResponse = apiInstance.previousPost()
            //result shouldBe ("TODO")
        }

        // to test queueGet
        should("test queueGet") {
            // uncomment below to test queueGet
            //val result : kotlin.collections.List<QueueResponseData> = apiInstance.queueGet()
            //result shouldBe ("TODO")
        }

    }
}
