/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.NowPlayingResponseData
import com.snowdango.bijouk.api.model.RPCArtwork
import com.snowdango.bijouk.api.model.RPCPlayParameters
import com.snowdango.bijouk.api.model.RPCPreview

class NowPlayingResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NowPlayingResponseData
        //val modelInstance = NowPlayingResponseData()

        // to test the property `albumName`
        should("test albumName") {
            // uncomment below to test the property
            //modelInstance.albumName shouldBe ("TODO")
        }

        // to test the property `artistName`
        should("test artistName") {
            // uncomment below to test the property
            //modelInstance.artistName shouldBe ("TODO")
        }

        // to test the property `currentPlaybackTime`
        should("test currentPlaybackTime") {
            // uncomment below to test the property
            //modelInstance.currentPlaybackTime shouldBe ("TODO")
        }

        // to test the property `durationInMillis`
        should("test durationInMillis") {
            // uncomment below to test the property
            //modelInstance.durationInMillis shouldBe ("TODO")
        }

        // to test the property `hasLyrics`
        should("test hasLyrics") {
            // uncomment below to test the property
            //modelInstance.hasLyrics shouldBe ("TODO")
        }

        // to test the property `isFavorites`
        should("test isFavorites") {
            // uncomment below to test the property
            //modelInstance.isFavorites shouldBe ("TODO")
        }

        // to test the property `inLibrary`
        should("test inLibrary") {
            // uncomment below to test the property
            //modelInstance.inLibrary shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `playParams`
        should("test playParams") {
            // uncomment below to test the property
            //modelInstance.playParams shouldBe ("TODO")
        }

        // to test the property `remainingTime`
        should("test remainingTime") {
            // uncomment below to test the property
            //modelInstance.remainingTime shouldBe ("TODO")
        }

        // to test the property `repeatMode`
        should("test repeatMode") {
            // uncomment below to test the property
            //modelInstance.repeatMode shouldBe ("TODO")
        }

        // to test the property `shuffleMode`
        should("test shuffleMode") {
            // uncomment below to test the property
            //modelInstance.shuffleMode shouldBe ("TODO")
        }

        // to test the property `artwork`
        should("test artwork") {
            // uncomment below to test the property
            //modelInstance.artwork shouldBe ("TODO")
        }

        // to test the property `audioLocale`
        should("test audioLocale") {
            // uncomment below to test the property
            //modelInstance.audioLocale shouldBe ("TODO")
        }

        // to test the property `audioTraits`
        should("test audioTraits") {
            // uncomment below to test the property
            //modelInstance.audioTraits shouldBe ("TODO")
        }

        // to test the property `composerName`
        should("test composerName") {
            // uncomment below to test the property
            //modelInstance.composerName shouldBe ("TODO")
        }

        // to test the property `discNumber`
        should("test discNumber") {
            // uncomment below to test the property
            //modelInstance.discNumber shouldBe ("TODO")
        }

        // to test the property `genreNames`
        should("test genreNames") {
            // uncomment below to test the property
            //modelInstance.genreNames shouldBe ("TODO")
        }

        // to test the property `hasTimeSyncedLyrics`
        should("test hasTimeSyncedLyrics") {
            // uncomment below to test the property
            //modelInstance.hasTimeSyncedLyrics shouldBe ("TODO")
        }

        // to test the property `isAppleDigitalMaster`
        should("test isAppleDigitalMaster") {
            // uncomment below to test the property
            //modelInstance.isAppleDigitalMaster shouldBe ("TODO")
        }

        // to test the property `isMasteredForItunes`
        should("test isMasteredForItunes") {
            // uncomment below to test the property
            //modelInstance.isMasteredForItunes shouldBe ("TODO")
        }

        // to test the property `isVocalAttenuationAllowed`
        should("test isVocalAttenuationAllowed") {
            // uncomment below to test the property
            //modelInstance.isVocalAttenuationAllowed shouldBe ("TODO")
        }

        // to test the property `isrc`
        should("test isrc") {
            // uncomment below to test the property
            //modelInstance.isrc shouldBe ("TODO")
        }

        // to test the property `previews`
        should("test previews") {
            // uncomment below to test the property
            //modelInstance.previews shouldBe ("TODO")
        }

        // to test the property `releaseDate`
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `trackNumber`
        should("test trackNumber") {
            // uncomment below to test the property
            //modelInstance.trackNumber shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
