/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.NowPlayingResponse
import com.snowdango.bijouk.api.model.NowPlayingResponseData

class NowPlayingResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NowPlayingResponse
        //val modelInstance = NowPlayingResponse()

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `info`
        should("test info") {
            // uncomment below to test the property
            //modelInstance.info shouldBe ("TODO")
        }

    }
}
