/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.PlaybackQueueMoveToPositionPostRequest

class PlaybackQueueMoveToPositionPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlaybackQueueMoveToPositionPostRequest
        //val modelInstance = PlaybackQueueMoveToPositionPostRequest()

        // to test the property `startIndex`
        should("test startIndex") {
            // uncomment below to test the property
            //modelInstance.startIndex shouldBe ("TODO")
        }

        // to test the property `destinationIndex`
        should("test destinationIndex") {
            // uncomment below to test the property
            //modelInstance.destinationIndex shouldBe ("TODO")
        }

    }
}
