/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.PlaybackPlayItemPostRequest

class PlaybackPlayItemPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlaybackPlayItemPostRequest
        //val modelInstance = PlaybackPlayItemPostRequest()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
