/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.PlaybackQueueChangeToIndexPostRequest

class PlaybackQueueChangeToIndexPostRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlaybackQueueChangeToIndexPostRequest
        //val modelInstance = PlaybackQueueChangeToIndexPostRequest()

        // to test the property `index`
        should("test index") {
            // uncomment below to test the property
            //modelInstance.index shouldBe ("TODO")
        }

    }
}
