/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.QueueResponseData
import com.snowdango.bijouk.api.model.QueueAsset
import com.snowdango.bijouk.api.model.QueueAttributes

class QueueResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueueResponseData
        //val modelInstance = QueueResponseData()

        // to test the property `assets`
        should("test assets") {
            // uncomment below to test the property
            //modelInstance.assets shouldBe ("TODO")
        }

        // to test the property `attributes`
        should("test attributes") {
            // uncomment below to test the property
            //modelInstance.attributes shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `playbackType`
        should("test playbackType") {
            // uncomment below to test the property
            //modelInstance.playbackType shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `songId`
        should("test songId") {
            // uncomment below to test the property
            //modelInstance.songId shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `assetURL`
        should("test assetURL") {
            // uncomment below to test the property
            //modelInstance.assetURL shouldBe ("TODO")
        }

        // to test the property `flavor`
        should("test flavor") {
            // uncomment below to test the property
            //modelInstance.flavor shouldBe ("TODO")
        }

    }
}
