/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.QueueChunks

class QueueChunksTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueueChunks
        //val modelInstance = QueueChunks()

        // to test the property `chunks`
        should("test chunks") {
            // uncomment below to test the property
            //modelInstance.chunks shouldBe ("TODO")
        }

    }
}
