/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.QueueAsset
import com.snowdango.bijouk.api.model.QueueChunks
import com.snowdango.bijouk.api.model.QueueMetadata

class QueueAssetTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueueAsset
        //val modelInstance = QueueAsset()

        // to test the property `URL`
        should("test URL") {
            // uncomment below to test the property
            //modelInstance.URL shouldBe ("TODO")
        }

        // to test the property `chunks`
        should("test chunks") {
            // uncomment below to test the property
            //modelInstance.chunks shouldBe ("TODO")
        }

        // to test the property `md5`
        should("test md5") {
            // uncomment below to test the property
            //modelInstance.md5 shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `artworkURL`
        should("test artworkURL") {
            // uncomment below to test the property
            //modelInstance.artworkURL shouldBe ("TODO")
        }

        // to test the property `downloadKey`
        should("test downloadKey") {
            // uncomment below to test the property
            //modelInstance.downloadKey shouldBe ("TODO")
        }

        // to test the property `fileSize`
        should("test fileSize") {
            // uncomment below to test the property
            //modelInstance.fileSize shouldBe ("TODO")
        }

        // to test the property `flavor`
        should("test flavor") {
            // uncomment below to test the property
            //modelInstance.flavor shouldBe ("TODO")
        }

    }
}
