/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.QueueAssetChunks

class QueueAssetChunksTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueueAssetChunks
        //val modelInstance = QueueAssetChunks()

        // to test the property `chunkSize`
        should("test chunkSize") {
            // uncomment below to test the property
            //modelInstance.chunkSize shouldBe ("TODO")
        }

        // to test the property `hashes`
        should("test hashes") {
            // uncomment below to test the property
            //modelInstance.hashes shouldBe ("TODO")
        }

    }
}
