/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.QueueMetadata

class QueueMetadataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueueMetadata
        //val modelInstance = QueueMetadata()

        // to test the property `artistName`
        should("test artistName") {
            // uncomment below to test the property
            //modelInstance.artistName shouldBe ("TODO")
        }

        // to test the property `bitRate`
        should("test bitRate") {
            // uncomment below to test the property
            //modelInstance.bitRate shouldBe ("TODO")
        }

        // to test the property `discCount`
        should("test discCount") {
            // uncomment below to test the property
            //modelInstance.discCount shouldBe ("TODO")
        }

        // to test the property `discNumber`
        should("test discNumber") {
            // uncomment below to test the property
            //modelInstance.discNumber shouldBe ("TODO")
        }

        // to test the property `duration`
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `explicit`
        should("test explicit") {
            // uncomment below to test the property
            //modelInstance.explicit shouldBe ("TODO")
        }

        // to test the property `fileExtension`
        should("test fileExtension") {
            // uncomment below to test the property
            //modelInstance.fileExtension shouldBe ("TODO")
        }

        // to test the property `gapless`
        should("test gapless") {
            // uncomment below to test the property
            //modelInstance.gapless shouldBe ("TODO")
        }

        // to test the property `genre`
        should("test genre") {
            // uncomment below to test the property
            //modelInstance.genre shouldBe ("TODO")
        }

        // to test the property `genreId`
        should("test genreId") {
            // uncomment below to test the property
            //modelInstance.genreId shouldBe ("TODO")
        }

        // to test the property `itemId`
        should("test itemId") {
            // uncomment below to test the property
            //modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `itemName`
        should("test itemName") {
            // uncomment below to test the property
            //modelInstance.itemName shouldBe ("TODO")
        }

        // to test the property `kind`
        should("test kind") {
            // uncomment below to test the property
            //modelInstance.kind shouldBe ("TODO")
        }

        // to test the property `playlistArtistName`
        should("test playlistArtistName") {
            // uncomment below to test the property
            //modelInstance.playlistArtistName shouldBe ("TODO")
        }

        // to test the property `sortAlbum`
        should("test sortAlbum") {
            // uncomment below to test the property
            //modelInstance.sortAlbum shouldBe ("TODO")
        }

        // to test the property `sortArtist`
        should("test sortArtist") {
            // uncomment below to test the property
            //modelInstance.sortArtist shouldBe ("TODO")
        }

        // to test the property `sortComposer`
        should("test sortComposer") {
            // uncomment below to test the property
            //modelInstance.sortComposer shouldBe ("TODO")
        }

        // to test the property `sortName`
        should("test sortName") {
            // uncomment below to test the property
            //modelInstance.sortName shouldBe ("TODO")
        }

        // to test the property `trackCount`
        should("test trackCount") {
            // uncomment below to test the property
            //modelInstance.trackCount shouldBe ("TODO")
        }

        // to test the property `trackNumber`
        should("test trackNumber") {
            // uncomment below to test the property
            //modelInstance.trackNumber shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `artistId`
        should("test artistId") {
            // uncomment below to test the property
            //modelInstance.artistId shouldBe ("TODO")
        }

        // to test the property `compilation`
        should("test compilation") {
            // uncomment below to test the property
            //modelInstance.compilation shouldBe ("TODO")
        }

        // to test the property `composerId`
        should("test composerId") {
            // uncomment below to test the property
            //modelInstance.composerId shouldBe ("TODO")
        }

        // to test the property `composerName`
        should("test composerName") {
            // uncomment below to test the property
            //modelInstance.composerName shouldBe ("TODO")
        }

        // to test the property `copyright`
        should("test copyright") {
            // uncomment below to test the property
            //modelInstance.copyright shouldBe ("TODO")
        }

        // to test the property `isMasteredForItunes`
        should("test isMasteredForItunes") {
            // uncomment below to test the property
            //modelInstance.isMasteredForItunes shouldBe ("TODO")
        }

        // to test the property `playlistId`
        should("test playlistId") {
            // uncomment below to test the property
            //modelInstance.playlistId shouldBe ("TODO")
        }

        // to test the property `playlistName`
        should("test playlistName") {
            // uncomment below to test the property
            //modelInstance.playlistName shouldBe ("TODO")
        }

        // to test the property `rank`
        should("test rank") {
            // uncomment below to test the property
            //modelInstance.rank shouldBe ("TODO")
        }

        // to test the property `releaseDate`
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `s`
        should("test s") {
            // uncomment below to test the property
            //modelInstance.s shouldBe ("TODO")
        }

        // to test the property `sampleRate`
        should("test sampleRate") {
            // uncomment below to test the property
            //modelInstance.sampleRate shouldBe ("TODO")
        }

        // to test the property `sortName`
        should("test sortName") {
            // uncomment below to test the property
            //modelInstance.sortName shouldBe ("TODO")
        }

        // to test the property `vendorId`
        should("test vendorId") {
            // uncomment below to test the property
            //modelInstance.vendorId shouldBe ("TODO")
        }

        // to test the property `xid`
        should("test xid") {
            // uncomment below to test the property
            //modelInstance.xid shouldBe ("TODO")
        }

    }
}
