/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.QueueState

class QueueStateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueueState
        //val modelInstance = QueueState()

        // to test the property `current`
        should("test current") {
            // uncomment below to test the property
            //modelInstance.current shouldBe ("TODO")
        }

    }
}
