/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.RPCArtwork

class RPCArtworkTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RPCArtwork
        //val modelInstance = RPCArtwork()

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `hasP3`
        should("test hasP3") {
            // uncomment below to test the property
            //modelInstance.hasP3 shouldBe ("TODO")
        }

        // to test the property `bgColor`
        should("test bgColor") {
            // uncomment below to test the property
            //modelInstance.bgColor shouldBe ("TODO")
        }

        // to test the property `textColor1`
        should("test textColor1") {
            // uncomment below to test the property
            //modelInstance.textColor1 shouldBe ("TODO")
        }

        // to test the property `textColor2`
        should("test textColor2") {
            // uncomment below to test the property
            //modelInstance.textColor2 shouldBe ("TODO")
        }

        // to test the property `textColor3`
        should("test textColor3") {
            // uncomment below to test the property
            //modelInstance.textColor3 shouldBe ("TODO")
        }

        // to test the property `textColor4`
        should("test textColor4") {
            // uncomment below to test the property
            //modelInstance.textColor4 shouldBe ("TODO")
        }

        // to test the property `gradient`
        should("test gradient") {
            // uncomment below to test the property
            //modelInstance.gradient shouldBe ("TODO")
        }

    }
}
