/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.snowdango.bijouk.api.model.RPCPlayParameters

class RPCPlayParametersTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RPCPlayParameters
        //val modelInstance = RPCPlayParameters()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `kind`
        should("test kind") {
            // uncomment below to test the property
            //modelInstance.kind shouldBe ("TODO")
        }

        // to test the property `isLibrary`
        should("test isLibrary") {
            // uncomment below to test the property
            //modelInstance.isLibrary shouldBe ("TODO")
        }

        // to test the property `reporting`
        should("test reporting") {
            // uncomment below to test the property
            //modelInstance.reporting shouldBe ("TODO")
        }

        // to test the property `catalogId`
        should("test catalogId") {
            // uncomment below to test the property
            //modelInstance.catalogId shouldBe ("TODO")
        }

        // to test the property `versionHash`
        should("test versionHash") {
            // uncomment below to test the property
            //modelInstance.versionHash shouldBe ("TODO")
        }

        // to test the property `reportingId`
        should("test reportingId") {
            // uncomment below to test the property
            //modelInstance.reportingId shouldBe ("TODO")
        }

    }
}
