/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Artwork
import com.snowdango.bijouk.api.model.EditorialNotes
import com.snowdango.bijouk.api.model.PlayParameters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artistName 
 * @param artwork 
 * @param genreNames 
 * @param isCompilation 
 * @param isComplete 
 * @param isMasteredForItunes 
 * @param isSingle 
 * @param name 
 * @param trackCount 
 * @param url 
 * @param artistUrl 
 * @param contentRating 
 * @param copyright 
 * @param editorialVideo 
 * @param inFavorites 
 * @param playParams 
 * @param recordLabel 
 * @param releaseDate 
 * @param upc 
 */
@Serializable

data class AlbumsAttributes (

    @SerialName(value = "artistName") @Required val artistName: kotlin.String,

    @SerialName(value = "artwork") @Required val artwork: Artwork,

    @SerialName(value = "genreNames") @Required val genreNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "isCompilation") @Required val isCompilation: kotlin.Boolean,

    @SerialName(value = "isComplete") @Required val isComplete: kotlin.Boolean,

    @SerialName(value = "isMasteredForItunes") @Required val isMasteredForItunes: kotlin.Boolean,

    @SerialName(value = "isSingle") @Required val isSingle: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "trackCount") @Required val trackCount: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "artistUrl") val artistUrl: kotlin.String? = null,

    @SerialName(value = "contentRating") val contentRating: kotlin.String? = null,

    @SerialName(value = "copyright") val copyright: kotlin.String? = null,

    @SerialName(value = "editorialVideo") val editorialVideo: EditorialNotes? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "recordLabel") val recordLabel: kotlin.String? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "upc") val upc: kotlin.String? = null

) {


}

