/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.AlbumsResponse
import com.snowdango.bijouk.api.model.ArtistsResponse
import com.snowdango.bijouk.api.model.LibraryAlbumsResponse
import com.snowdango.bijouk.api.model.LibraryArtistsResponse
import com.snowdango.bijouk.api.model.LibraryPlaylistFoldersResponse
import com.snowdango.bijouk.api.model.LibraryPlaylistsResponse
import com.snowdango.bijouk.api.model.LibrarySearchResponse
import com.snowdango.bijouk.api.model.LibrarySongsResponse
import com.snowdango.bijouk.api.model.PlaylistsResponse
import com.snowdango.bijouk.api.model.RelationshipViewAlbumsResponse
import com.snowdango.bijouk.api.model.RelationshipViewLibraryAlbumsResponse
import com.snowdango.bijouk.api.model.RelationshipViewLibraryAlbumsResponseData
import com.snowdango.bijouk.api.model.RelationshipViewLibrarySongsResponse
import com.snowdango.bijouk.api.model.RelationshipViewSongsResponse
import com.snowdango.bijouk.api.model.SearchResponse
import com.snowdango.bijouk.api.model.SongsResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * 
 *
 */
@Serializable(with = ApiV1AmapiRunV3Post200Response.ApiV1AmapiRunV3Post200ResponseSerializer::class)
data class ApiV1AmapiRunV3Post200Response(var actualInstance: Any? = null) {

    object ApiV1AmapiRunV3Post200ResponseSerializer : KSerializer<ApiV1AmapiRunV3Post200Response> {
        override val descriptor: SerialDescriptor = buildClassSerialDescriptor("ApiV1AmapiRunV3Post200Response") {
            element("type", JsonPrimitive.serializer().descriptor)
            element("actualInstance", JsonElement.serializer().descriptor)
        }

        override fun serialize(encoder: Encoder, value: ApiV1AmapiRunV3Post200Response) {
            val jsonEncoder = encoder as? JsonEncoder ?: throw SerializationException("ApiV1AmapiRunV3Post200Response can only be serialized with Json")

            when (val instance = value.actualInstance) {
                is SearchResponse -> jsonEncoder.encodeSerializableValue(SearchResponse.serializer(), instance)
                is SongsResponse -> jsonEncoder.encodeSerializableValue(SongsResponse.serializer(), instance)
                is AlbumsResponse -> jsonEncoder.encodeSerializableValue(AlbumsResponse.serializer(), instance)
                is ArtistsResponse -> jsonEncoder.encodeSerializableValue(ArtistsResponse.serializer(), instance)
                is PlaylistsResponse -> jsonEncoder.encodeSerializableValue(PlaylistsResponse.serializer(), instance)
                is LibrarySearchResponse -> jsonEncoder.encodeSerializableValue(LibrarySearchResponse.serializer(), instance)
                is LibrarySongsResponse -> jsonEncoder.encodeSerializableValue(LibrarySongsResponse.serializer(), instance)
                is LibraryAlbumsResponse -> jsonEncoder.encodeSerializableValue(LibraryAlbumsResponse.serializer(), instance)
                is LibraryArtistsResponse -> jsonEncoder.encodeSerializableValue(LibraryArtistsResponse.serializer(), instance)
                is LibraryPlaylistsResponse -> jsonEncoder.encodeSerializableValue(LibraryPlaylistsResponse.serializer(), instance)
                is LibraryPlaylistFoldersResponse -> jsonEncoder.encodeSerializableValue(LibraryPlaylistFoldersResponse.serializer(), instance)
                is RelationshipViewSongsResponse -> jsonEncoder.encodeSerializableValue(RelationshipViewSongsResponse.serializer(), instance)
                is RelationshipViewLibrarySongsResponse -> jsonEncoder.encodeSerializableValue(RelationshipViewLibrarySongsResponse.serializer(), instance)
                is RelationshipViewAlbumsResponse -> jsonEncoder.encodeSerializableValue(RelationshipViewAlbumsResponse.serializer(), instance)
                is RelationshipViewLibraryAlbumsResponse -> jsonEncoder.encodeSerializableValue(RelationshipViewLibraryAlbumsResponse.serializer(), instance)
                null -> jsonEncoder.encodeJsonElement(JsonNull)
                else -> throw SerializationException("Unknown type in actualInstance: ${instance::class}")
            }
        }

        override fun deserialize(decoder: Decoder): ApiV1AmapiRunV3Post200Response {
            val jsonDecoder = decoder as? JsonDecoder ?: throw SerializationException("ApiV1AmapiRunV3Post200Response can only be deserialized with Json")
            val jsonElement = jsonDecoder.decodeJsonElement()

            val errorMessages = mutableListOf<String>()

            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<SearchResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as SearchResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<SongsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as SongsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<AlbumsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as AlbumsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<ArtistsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as ArtistsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<PlaylistsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as PlaylistsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<LibrarySearchResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as LibrarySearchResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<LibrarySongsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as LibrarySongsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<LibraryAlbumsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as LibraryAlbumsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<LibraryArtistsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as LibraryArtistsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<LibraryPlaylistsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as LibraryPlaylistsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<LibraryPlaylistFoldersResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as LibraryPlaylistFoldersResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<RelationshipViewSongsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as RelationshipViewSongsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<RelationshipViewLibrarySongsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as RelationshipViewLibrarySongsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<RelationshipViewAlbumsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as RelationshipViewAlbumsResponse: ${e.message}")
            }
            try {
                val instance = jsonDecoder.json.decodeFromJsonElement<RelationshipViewLibraryAlbumsResponse>(jsonElement)
                return ApiV1AmapiRunV3Post200Response(actualInstance = instance)
            } catch (e: Exception) {
                errorMessages.add("Failed to deserialize as RelationshipViewLibraryAlbumsResponse: ${e.message}")
            }

            throw SerializationException("Cannot deserialize ApiV1AmapiRunV3Post200Response. Tried: ${errorMessages.joinToString(", ")}")
        }
    }
}

