/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Stations

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param href 
 * @param `data` 
 */
@Serializable

data class ArtistsRelationshipsDefaultPlayableContent (

    @SerialName(value = "href") @Required val href: kotlin.String,

    @SerialName(value = "data") @Required val `data`: kotlin.collections.List<Stations>

) {


}

