/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Artwork
import com.snowdango.bijouk.api.model.EditorialNotes

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param genreNames 
 * @param name 
 * @param url 
 * @param artwork 
 * @param editorialNotes 
 * @param inFavorites 
 */
@Serializable

data class ArtistsAttributes (

    @SerialName(value = "genreNames") @Required val genreNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "artwork") val artwork: Artwork? = null,

    @SerialName(value = "editorialNotes") val editorialNotes: EditorialNotes? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null

) {


}

