/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.ArtistsAttributes
import com.snowdango.bijouk.api.model.ArtistsRelationships

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param type 
 * @param href 
 * @param attributes 
 * @param relationships 
 * @param views 
 */
@Serializable

data class Artists (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "href") @Required val href: kotlin.String,

    @SerialName(value = "attributes") val attributes: ArtistsAttributes? = null,

    @SerialName(value = "relationships") val relationships: ArtistsRelationships? = null,

    @SerialName(value = "views") val views: kotlin.String? = null

) {


}

