/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param height 
 * @param width 
 * @param url 
 * @param bgColor 
 * @param textColor1 
 * @param textColor2 
 * @param textColor3 
 * @param textColor4 
 */
@Serializable

data class Artwork (

    @SerialName(value = "height") @Required val height: kotlin.Int,

    @SerialName(value = "width") @Required val width: kotlin.Int,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "bgColor") val bgColor: kotlin.String? = null,

    @SerialName(value = "textColor1") val textColor1: kotlin.String? = null,

    @SerialName(value = "textColor2") val textColor2: kotlin.String? = null,

    @SerialName(value = "textColor3") val textColor3: kotlin.String? = null,

    @SerialName(value = "textColor4") val textColor4: kotlin.String? = null

) {


}

