/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param short 
 * @param standard 
 * @param name 
 * @param tagline 
 */
@Serializable

data class EditorialNotes (

    @SerialName(value = "short") val short: kotlin.String? = null,

    @SerialName(value = "standard") val standard: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "tagline") val tagline: kotlin.String? = null

) {


}

