/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.LibraryArtwork
import com.snowdango.bijouk.api.model.PlayParameters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artistName 
 * @param name 
 * @param trackCount 
 * @param genreNames 
 * @param artwork 
 * @param contentRating 
 * @param dateAdded 
 * @param playParams 
 * @param releaseDate 
 * @param inFavorites 
 */
@Serializable

data class LibraryAlbumsAttributes (

    @SerialName(value = "artistName") @Required val artistName: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "trackCount") @Required val trackCount: kotlin.Int,

    @SerialName(value = "genreNames") @Required val genreNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "artwork") val artwork: LibraryArtwork? = null,

    @SerialName(value = "contentRating") val contentRating: kotlin.String? = null,

    @SerialName(value = "dateAdded") val dateAdded: kotlin.String? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null

) {


}

