/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param inFavorites 
 */
@Serializable

data class LibraryArtistsAttributes (

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null

) {


}

