/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.LibraryPlaylistsRelationshipsCatalog

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param catalog 
 */
@Serializable

data class LibraryPlaylistsRelationships (

    @SerialName(value = "catalog") val catalog: LibraryPlaylistsRelationshipsCatalog? = null

) {


}

