/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.LibraryArtwork
import com.snowdango.bijouk.api.model.PlayParameters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param albumName 
 * @param artistName 
 * @param durationInMillis 
 * @param genreNames 
 * @param hasLyrics 
 * @param name 
 * @param artwork 
 * @param contentRating 
 * @param discNumber 
 * @param inFavorites 
 * @param playParams 
 * @param releaseDate 
 * @param trackNumber 
 */
@Serializable

data class LibrarySongsAttributes (

    @SerialName(value = "albumName") @Required val albumName: kotlin.String,

    @SerialName(value = "artistName") @Required val artistName: kotlin.String,

    @SerialName(value = "durationInMillis") @Required val durationInMillis: kotlin.Long,

    @SerialName(value = "genreNames") @Required val genreNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "hasLyrics") @Required val hasLyrics: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "artwork") val artwork: LibraryArtwork? = null,

    @SerialName(value = "contentRating") val contentRating: kotlin.String? = null,

    @SerialName(value = "discNumber") val discNumber: kotlin.Int? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "trackNumber") val trackNumber: kotlin.Int? = null

) {


}

