/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.DescriptionAttribute
import com.snowdango.bijouk.api.model.LibraryArtwork
import com.snowdango.bijouk.api.model.PlayParameters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param canEdit 
 * @param hasCatalog 
 * @param name 
 * @param isPublic 
 * @param artwork 
 * @param dateAdded 
 * @param description 
 * @param playParams 
 * @param trackTypes 
 * @param inFavorites 
 */
@Serializable

data class LibraryPlaylistsAttributes (

    @SerialName(value = "canEdit") @Required val canEdit: kotlin.Boolean,

    @SerialName(value = "hasCatalog") @Required val hasCatalog: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "isPublic") @Required val isPublic: kotlin.Boolean,

    @SerialName(value = "artwork") val artwork: LibraryArtwork? = null,

    @SerialName(value = "dateAdded") val dateAdded: kotlin.String? = null,

    @SerialName(value = "description") val description: DescriptionAttribute? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "trackTypes") val trackTypes: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null

) {


}

