/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.LibrarySearchResponseDataResultsLibraryAlbums
import com.snowdango.bijouk.api.model.LibrarySearchResponseDataResultsLibraryArtists
import com.snowdango.bijouk.api.model.LibrarySearchResponseDataResultsLibraryPlaylists
import com.snowdango.bijouk.api.model.LibrarySearchResponseDataResultsLibrarySongs

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param libraryAlbums 
 * @param libraryArtists 
 * @param libraryPlaylists 
 * @param librarySongs 
 */
@Serializable

data class LibrarySearchResponseDataResults (

    @SerialName(value = "library-albums") val libraryAlbums: LibrarySearchResponseDataResultsLibraryAlbums? = null,

    @SerialName(value = "library-artists") val libraryArtists: LibrarySearchResponseDataResultsLibraryArtists? = null,

    @SerialName(value = "library-playlists") val libraryPlaylists: LibrarySearchResponseDataResultsLibraryPlaylists? = null,

    @SerialName(value = "library-songs") val librarySongs: LibrarySearchResponseDataResultsLibrarySongs? = null

) {


}

