/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Albums

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param href 
 */
@Serializable

data class LibraryAlbumsRelationshipsCatalog (

    @SerialName(value = "data") @Required val `data`: kotlin.collections.List<Albums>,

    @SerialName(value = "href") val href: kotlin.String? = null

) {


}

