/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.NowPlayingResponseData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status 
 * @param info 
 */
@Serializable

data class NowPlayingResponse (

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "info") @Required val info: NowPlayingResponseData

) {


}

