/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.RPCArtwork
import com.snowdango.bijouk.api.model.RPCPlayParameters
import com.snowdango.bijouk.api.model.RPCPreview

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param albumName 
 * @param artistName 
 * @param currentPlaybackTime 
 * @param durationInMillis 
 * @param hasLyrics 
 * @param inLibrary 
 * @param name 
 * @param playParams 
 * @param remainingTime 
 * @param repeatMode 
 * @param shuffleMode 
 * @param artwork 
 * @param audioLocale 
 * @param audioTraits 
 * @param composerName 
 * @param discNumber 
 * @param genreNames 
 * @param hasTimeSyncedLyrics 
 * @param isFavorites 
 * @param isAppleDigitalMaster 
 * @param isMasteredForItunes 
 * @param isVocalAttenuationAllowed 
 * @param isrc 
 * @param previews 
 * @param releaseDate 
 * @param trackNumber 
 * @param url 
 */
@Serializable

data class NowPlayingResponseData (

    @SerialName(value = "albumName") @Required val albumName: kotlin.String,

    @SerialName(value = "artistName") @Required val artistName: kotlin.String,

    @SerialName(value = "currentPlaybackTime") @Required val currentPlaybackTime: kotlin.Double,

    @SerialName(value = "durationInMillis") @Required val durationInMillis: kotlin.Int,

    @SerialName(value = "hasLyrics") @Required val hasLyrics: kotlin.Boolean,

    @SerialName(value = "inLibrary") @Required val inLibrary: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "playParams") @Required val playParams: RPCPlayParameters,

    @SerialName(value = "remainingTime") @Required val remainingTime: kotlin.Double,

    @SerialName(value = "repeatMode") @Required val repeatMode: kotlin.Int,

    @SerialName(value = "shuffleMode") @Required val shuffleMode: kotlin.Int,

    @SerialName(value = "artwork") val artwork: RPCArtwork? = null,

    @SerialName(value = "audioLocale") val audioLocale: kotlin.String? = null,

    @SerialName(value = "audioTraits") val audioTraits: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "composerName") val composerName: kotlin.String? = null,

    @SerialName(value = "discNumber") val discNumber: kotlin.Int? = null,

    @SerialName(value = "genreNames") val genreNames: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "hasTimeSyncedLyrics") val hasTimeSyncedLyrics: kotlin.Boolean? = null,

    @SerialName(value = "isFavorites") val isFavorites: kotlin.Boolean? = null,

    @SerialName(value = "isAppleDigitalMaster") val isAppleDigitalMaster: kotlin.Boolean? = null,

    @SerialName(value = "isMasteredForItunes") val isMasteredForItunes: kotlin.Boolean? = null,

    @SerialName(value = "isVocalAttenuationAllowed") val isVocalAttenuationAllowed: kotlin.Boolean? = null,

    @SerialName(value = "isrc") val isrc: kotlin.String? = null,

    @SerialName(value = "previews") val previews: kotlin.collections.List<RPCPreview>? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "trackNumber") val trackNumber: kotlin.Int? = null,

    @SerialName(value = "url") val url: kotlin.String? = null

) {


}

