/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status 
 * @param `value` 
 */
@Serializable

data class PlaybackShuffleModeGet200Response (

    @SerialName(value = "status") @Required val status: kotlin.String,

    @SerialName(value = "value") @Required val `value`: kotlin.Int

) {


}

