/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param startIndex 
 * @param destinationIndex 
 */
@Serializable

data class PlaybackQueueMoveToPositionPostRequest (

    @SerialName(value = "startIndex") @Required val startIndex: kotlin.Int,

    @SerialName(value = "destinationIndex") @Required val destinationIndex: kotlin.Int

) {


}

