/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Playlists

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param next 
 * @param `data` 
 */
@Serializable

data class PlaylistsResponseData (

    @SerialName(value = "next") val next: kotlin.String? = null,

    @SerialName(value = "data") val `data`: kotlin.collections.List<Playlists>? = null

) {


}

