/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param id 
 */
@Serializable

data class PlayRequestBody (

    @SerialName(value = "type") @Required val type: PlayRequestBody.Type,

    @SerialName(value = "id") @Required val id: kotlin.String

) {

    /**
     * 
     *
     * Values: SONGS,PLAYLISTS,ALBUMS,ARTISTS,STATIONS
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "songs") SONGS("songs"),
        @SerialName(value = "playlists") PLAYLISTS("playlists"),
        @SerialName(value = "albums") ALBUMS("albums"),
        @SerialName(value = "artists") ARTISTS("artists"),
        @SerialName(value = "stations") STATIONS("stations");
    }

}

