/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Artwork
import com.snowdango.bijouk.api.model.DescriptionAttribute
import com.snowdango.bijouk.api.model.PlayParameters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param isChart 
 * @param name 
 * @param playlistType 
 * @param url 
 * @param artwork 
 * @param curatorName 
 * @param description 
 * @param lastModifiedDate 
 * @param playParams 
 * @param trackTypes 
 * @param inFavorites 
 */
@Serializable

data class PlaylistsAttributes (

    @SerialName(value = "isChart") @Required val isChart: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "playlistType") @Required val playlistType: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "artwork") val artwork: Artwork? = null,

    @SerialName(value = "curatorName") val curatorName: kotlin.String? = null,

    @SerialName(value = "description") val description: DescriptionAttribute? = null,

    @SerialName(value = "lastModifiedDate") val lastModifiedDate: kotlin.String? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "trackTypes") val trackTypes: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null

) {


}

