/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Artwork

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param url 
 * @param artwork 
 * @param hlsUrl 
 */
@Serializable

data class Preview (

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "artwork") val artwork: Artwork? = null,

    @SerialName(value = "hlsUrl") val hlsUrl: kotlin.String? = null

) {


}

