/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param chunkSize 
 * @param hashes 
 */
@Serializable

data class QueueAssetChunks (

    @SerialName(value = "chunkSize") val chunkSize: kotlin.Int? = null,

    @SerialName(value = "hashes") val hashes: kotlin.collections.List<kotlin.String>? = null

) {


}

