/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.RPCArtwork
import com.snowdango.bijouk.api.model.RPCPlayParameters
import com.snowdango.bijouk.api.model.RPCPreview

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param albumName 
 * @param discNumber 
 * @param durationInMillis 
 * @param genreNames 
 * @param hasLyrics 
 * @param name 
 * @param trackNumber 
 * @param artistName 
 * @param artwork 
 * @param audioLocale 
 * @param audioTraits 
 * @param composerName 
 * @param currentPlaybackTime 
 * @param hasTimeSyncedLyrics 
 * @param isAppleDigitalMaster 
 * @param isMasteredForItunes 
 * @param isVocalAttenuationAllowed 
 * @param isrc 
 * @param playParams 
 * @param previews 
 * @param releaseDate 
 * @param remainingTime 
 * @param url 
 */
@Serializable

data class QueueAttributes (

    @SerialName(value = "albumName") @Required val albumName: kotlin.String,

    @SerialName(value = "discNumber") @Required val discNumber: kotlin.Double,

    @SerialName(value = "durationInMillis") @Required val durationInMillis: kotlin.Double,

    @SerialName(value = "genreNames") @Required val genreNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "hasLyrics") @Required val hasLyrics: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "trackNumber") @Required val trackNumber: kotlin.Double,

    @SerialName(value = "artistName") val artistName: kotlin.String? = null,

    @SerialName(value = "artwork") val artwork: RPCArtwork? = null,

    @SerialName(value = "audioLocale") val audioLocale: kotlin.String? = null,

    @SerialName(value = "audioTraits") val audioTraits: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "composerName") val composerName: kotlin.String? = null,

    @SerialName(value = "currentPlaybackTime") val currentPlaybackTime: kotlin.Double? = null,

    @SerialName(value = "hasTimeSyncedLyrics") val hasTimeSyncedLyrics: kotlin.Boolean? = null,

    @SerialName(value = "isAppleDigitalMaster") val isAppleDigitalMaster: kotlin.Boolean? = null,

    @SerialName(value = "isMasteredForItunes") val isMasteredForItunes: kotlin.Boolean? = null,

    @SerialName(value = "isVocalAttenuationAllowed") val isVocalAttenuationAllowed: kotlin.Boolean? = null,

    @SerialName(value = "isrc") val isrc: kotlin.String? = null,

    @SerialName(value = "playParams") val playParams: RPCPlayParameters? = null,

    @SerialName(value = "previews") val previews: kotlin.collections.List<RPCPreview>? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "remainingTime") val remainingTime: kotlin.Double? = null,

    @SerialName(value = "url") val url: kotlin.String? = null

) {


}

