/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.QueueAsset
import com.snowdango.bijouk.api.model.QueueAttributes
import com.snowdango.bijouk.api.model.QueueResponseDataState

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param assets 
 * @param attributes 
 * @param id 
 * @param playbackType 
 * @param type 
 * @param songId 
 * @param state 
 * @param assetURL 
 * @param flavor 
 */
@Serializable

data class QueueResponseData (

    @SerialName(value = "assets") @Required val assets: kotlin.collections.List<QueueAsset>,

    @SerialName(value = "attributes") @Required val attributes: QueueAttributes,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "playbackType") @Required val playbackType: kotlin.Int,

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "_songId") val songId: kotlin.String? = null,

    @SerialName(value = "_state") val state: QueueResponseDataState? = null,

    @SerialName(value = "assetURL") val assetURL: kotlin.String? = null,

    @SerialName(value = "flavor") val flavor: kotlin.String? = null

) {


}

