/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.QueueAssetChunks
import com.snowdango.bijouk.api.model.QueueMetadata

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param URL 
 * @param md5 
 * @param metadata 
 * @param artworkURL 
 * @param chunks 
 * @param downloadKey 
 * @param fileSize 
 * @param flavor 
 */
@Serializable

data class QueueAsset (

    @SerialName(value = "URL") @Required val URL: kotlin.String,

    @SerialName(value = "md5") @Required val md5: kotlin.String,

    @SerialName(value = "metadata") @Required val metadata: QueueMetadata,

    @SerialName(value = "artworkURL") val artworkURL: kotlin.String? = null,

    @SerialName(value = "chunks") val chunks: QueueAssetChunks? = null,

    @SerialName(value = "downloadKey") val downloadKey: kotlin.String? = null,

    @SerialName(value = "file-size") val fileSize: kotlin.Int? = null,

    @SerialName(value = "flavor") val flavor: kotlin.String? = null

) {


}

