/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artistName 
 * @param bitRate 
 * @param discCount 
 * @param discNumber 
 * @param duration 
 * @param explicit 
 * @param fileExtension 
 * @param gapless 
 * @param genre 
 * @param itemId 
 * @param itemName 
 * @param kind 
 * @param playlistArtistName 
 * @param sortAlbum 
 * @param sortArtist 
 * @param sortComposer 
 * @param sortName 
 * @param trackCount 
 * @param trackNumber 
 * @param year 
 * @param artistId 
 * @param compilation 
 * @param composerId 
 * @param composerName 
 * @param copyright 
 * @param genreId 
 * @param isMasteredForItunes 
 * @param playlistId 
 * @param playlistName 
 * @param rank 
 * @param releaseDate 
 * @param s 
 * @param sampleRate 
 * @param vendorId 
 * @param xid 
 */
@Serializable

data class QueueMetadata (

    @SerialName(value = "artistName") @Required val artistName: kotlin.String,

    @SerialName(value = "bitRate") @Required val bitRate: kotlin.Int,

    @SerialName(value = "discCount") @Required val discCount: kotlin.Int,

    @SerialName(value = "discNumber") @Required val discNumber: kotlin.Int,

    @SerialName(value = "duration") @Required val duration: kotlin.Int,

    @SerialName(value = "explicit") @Required val explicit: kotlin.Int,

    @SerialName(value = "fileExtension") @Required val fileExtension: kotlin.String,

    @SerialName(value = "gapless") @Required val gapless: kotlin.Boolean,

    @SerialName(value = "genre") @Required val genre: kotlin.String,

    @SerialName(value = "itemId") @Required val itemId: kotlin.String,

    @SerialName(value = "itemName") @Required val itemName: kotlin.String,

    @SerialName(value = "kind") @Required val kind: kotlin.String,

    @SerialName(value = "playlistArtistName") @Required val playlistArtistName: kotlin.String,

    @SerialName(value = "sort-album") @Required val sortAlbum: kotlin.String,

    @SerialName(value = "sort-artist") @Required val sortArtist: kotlin.String,

    @SerialName(value = "sort-composer") @Required val sortComposer: kotlin.String,

    @SerialName(value = "sort-name") @Required val sortName: kotlin.String,

    @SerialName(value = "trackCount") @Required val trackCount: kotlin.Int,

    @SerialName(value = "trackNumber") @Required val trackNumber: kotlin.Int,

    @SerialName(value = "year") @Required val year: kotlin.Int,

    @SerialName(value = "artistId") val artistId: kotlin.String? = null,

    @SerialName(value = "compilation") val compilation: kotlin.Boolean? = null,

    @SerialName(value = "composerId") val composerId: kotlin.String? = null,

    @SerialName(value = "composerName") val composerName: kotlin.String? = null,

    @SerialName(value = "copyright") val copyright: kotlin.String? = null,

    @SerialName(value = "genreId") val genreId: kotlin.Int? = null,

    @SerialName(value = "isMasteredForItunes") val isMasteredForItunes: kotlin.Boolean? = null,

    @SerialName(value = "playlistId") val playlistId: kotlin.String? = null,

    @SerialName(value = "playlistName") val playlistName: kotlin.String? = null,

    @SerialName(value = "rank") val rank: kotlin.Int? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "s") val s: kotlin.Int? = null,

    @SerialName(value = "sampleRate") val sampleRate: kotlin.Int? = null,

    @SerialName(value = "vendorId") val vendorId: kotlin.Int? = null,

    @SerialName(value = "xid") val xid: kotlin.String? = null

) {


}

