/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Albums

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param attributes 
 * @param meta 
 * @param next 
 */
@Serializable

data class RelationshipViewAlbumsResponseData (

    @SerialName(value = "data") @Required val `data`: kotlin.collections.List<Albums>,

    @SerialName(value = "attributes") val attributes: kotlin.String? = null,

    @SerialName(value = "meta") val meta: kotlin.String? = null,

    @SerialName(value = "next") val next: kotlin.String? = null

) {


}

