/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param kind 
 * @param isLibrary 
 * @param reporting 
 * @param catalogId 
 * @param versionHash 
 * @param reportingId 
 */
@Serializable

data class RPCPlayParameters (

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "kind") @Required val kind: kotlin.String,

    @SerialName(value = "isLibrary") val isLibrary: kotlin.Boolean? = null,

    @SerialName(value = "reporting") val reporting: kotlin.Boolean? = null,

    @SerialName(value = "catalogId") val catalogId: kotlin.String? = null,

    @SerialName(value = "versionHash") val versionHash: kotlin.String? = null,

    @SerialName(value = "reportingId") val reportingId: kotlin.String? = null

) {


}

