/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.SearchResponseDataResultsAlbums
import com.snowdango.bijouk.api.model.SearchResponseDataResultsArtists
import com.snowdango.bijouk.api.model.SearchResponseDataResultsPlaylists
import com.snowdango.bijouk.api.model.SearchResponseDataResultsSongs

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param albums 
 * @param artists 
 * @param playlists 
 * @param songs 
 */
@Serializable

data class SearchResponseDataResults (

    @SerialName(value = "albums") val albums: SearchResponseDataResultsAlbums? = null,

    @SerialName(value = "artists") val artists: SearchResponseDataResultsArtists? = null,

    @SerialName(value = "playlists") val playlists: SearchResponseDataResultsPlaylists? = null,

    @SerialName(value = "songs") val songs: SearchResponseDataResultsSongs? = null

) {


}

