/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.SongsAttributes

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id 
 * @param type 
 * @param href 
 * @param attributes 
 * @param relationships 
 */
@Serializable

data class Songs (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "type") val type: kotlin.String? = null,

    @SerialName(value = "href") val href: kotlin.String? = null,

    @SerialName(value = "attributes") val attributes: SongsAttributes? = null,

    @SerialName(value = "relationships") val relationships: kotlin.String? = null

) {


}

