/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Artwork
import com.snowdango.bijouk.api.model.EditorialNotes
import com.snowdango.bijouk.api.model.PlayParameters
import com.snowdango.bijouk.api.model.Preview

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param albumName 
 * @param artistName 
 * @param artwork 
 * @param durationInMillis 
 * @param genreNames 
 * @param hasLyrics 
 * @param isAppleDigitalMaster 
 * @param name 
 * @param previews 
 * @param url 
 * @param artistUrl 
 * @param attribution 
 * @param composerName 
 * @param contentRating 
 * @param discNumber 
 * @param editorialNotes 
 * @param inFavorites 
 * @param isrc 
 * @param movementCount 
 * @param movementName 
 * @param movementNumber 
 * @param playParams 
 * @param releaseDate 
 * @param trackNumber 
 * @param workName 
 */
@Serializable

data class SongsAttributes (

    @SerialName(value = "albumName") @Required val albumName: kotlin.String,

    @SerialName(value = "artistName") @Required val artistName: kotlin.String,

    @SerialName(value = "artwork") @Required val artwork: Artwork,

    @SerialName(value = "durationInMillis") @Required val durationInMillis: kotlin.Long,

    @SerialName(value = "genreNames") @Required val genreNames: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "hasLyrics") @Required val hasLyrics: kotlin.Boolean,

    @SerialName(value = "isAppleDigitalMaster") @Required val isAppleDigitalMaster: kotlin.Boolean,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "previews") @Required val previews: kotlin.collections.List<Preview>,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "artistUrl") val artistUrl: kotlin.String? = null,

    @SerialName(value = "attribution") val attribution: kotlin.String? = null,

    @SerialName(value = "composerName") val composerName: kotlin.String? = null,

    @SerialName(value = "contentRating") val contentRating: kotlin.String? = null,

    @SerialName(value = "discNumber") val discNumber: kotlin.Int? = null,

    @SerialName(value = "editorialNotes") val editorialNotes: EditorialNotes? = null,

    @SerialName(value = "inFavorites") val inFavorites: kotlin.Boolean? = null,

    @SerialName(value = "isrc") val isrc: kotlin.String? = null,

    @SerialName(value = "movementCount") val movementCount: kotlin.Int? = null,

    @SerialName(value = "movementName") val movementName: kotlin.String? = null,

    @SerialName(value = "movementNumber") val movementNumber: kotlin.Int? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "releaseDate") val releaseDate: kotlin.String? = null,

    @SerialName(value = "trackNumber") val trackNumber: kotlin.Int? = null,

    @SerialName(value = "workName") val workName: kotlin.String? = null

) {


}

