/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import com.snowdango.bijouk.api.model.Artwork
import com.snowdango.bijouk.api.model.EditorialNotes
import com.snowdango.bijouk.api.model.PlayParameters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artwork 
 * @param isLive 
 * @param mediaKind 
 * @param name 
 * @param url 
 * @param durationInMillis 
 * @param editorialNotes 
 * @param episodeNumber 
 * @param contentRating 
 * @param playParams 
 * @param stationProviderName 
 */
@Serializable

data class StationsAttributes (

    @SerialName(value = "artwork") @Required val artwork: Artwork,

    @SerialName(value = "isLive") @Required val isLive: kotlin.Boolean,

    @SerialName(value = "mediaKind") @Required val mediaKind: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "durationInMillis") val durationInMillis: kotlin.Long? = null,

    @SerialName(value = "editorialNotes") val editorialNotes: EditorialNotes? = null,

    @SerialName(value = "episodeNumber") val episodeNumber: kotlin.String? = null,

    @SerialName(value = "contentRating") val contentRating: kotlin.String? = null,

    @SerialName(value = "playParams") val playParams: PlayParameters? = null,

    @SerialName(value = "stationProviderName") val stationProviderName: kotlin.String? = null

) {


}

