/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.snowdango.bijouk.api.model

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Stations relationships object
 *
 * This data class represents the relationships field in the Stations response.
 * According to the OpenAPI specification, this is defined as an object with no properties.
 * It is kept as an empty data class to properly deserialize JSON responses where
 * relationships is an empty object: "relationships": {}
 */
@Serializable

data class StationsRelationships (
    // Empty object as per OpenAPI spec - no properties defined
) {


}
