name: Test

on:
  pull_request:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: create local.properties
        run: |
          touch local.properties
          echo "debug.keypass=${{ secrets.DEBUG_KEY_PASS }}" >> local.properties
          echo "debug.storepass=${{ secrets.DEBUG_STORE_PASS }}" >> local.properties
      - name: create debug google-services.json
        run: |
          touch app/src/debug/google-services.json
          echo "${{ secrets.DEBUG_GOOGLE_SERVICES_BASE64 }}" | base64 -d > app/src/debug/google-services.json
      - name: create debug keystore
        run: |
          touch debug.keystore
          echo "${{ secrets.DEBUG_KEY_STORE }}" | base64 -d > debug.keystore
      - name: Build with Gradle
        run: ./gradlew assembleDebug
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: create local.properties
        run: |
          touch local.properties
          echo "debug.keypass=${{ secrets.DEBUG_KEY_PASS }}" >> local.properties
          echo "debug.storepass=${{ secrets.DEBUG_STORE_PASS }}" >> local.properties
      - name: create debug google-services.json
        run: |
          touch app/src/debug/google-services.json
          echo "${{ secrets.DEBUG_GOOGLE_SERVICES_BASE64 }}" | base64 -d > app/src/debug/google-services.json
      - name: create debug keystore
        run: |
          touch debug.keystore
          echo "${{ secrets.DEBUG_KEY_STORE }}" | base64 -d > debug.keystore
      - name: Build with Gradle
        run: ./gradlew detekt --auto-correct

